server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: resilience4j
          uri: https://github.com/IsaacCRS17/MICROSERVICIOS-SPRINGBOOT
          search-paths: config-data
  application:
    name: config-service

